# Generated by Django 5.1.7 on 2025-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twicky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twicky',
            name='text',
            field=models.TextField(default='Default Text', max_length=240),
        ),
    ]
