# Generated by Django 5.1.7 on 2025-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twicky', '0002_twicky_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twicky',
            name='text',
            field=models.TextField(default='', max_length=240),
        ),
    ]
